# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 320, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txttaikhoan = QtWidgets.QLineEdit(self.centralwidget)
        self.txttaikhoan.setGeometry(QtCore.QRect(150, 270, 141, 31))
        self.txttaikhoan.setObjectName("txttaikhoan")
        self.txtmatkhau = QtWidgets.QLineEdit(self.centralwidget)
        self.txtmatkhau.setGeometry(QtCore.QRect(150, 320, 141, 31))
        self.txtmatkhau.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtmatkhau.setObjectName("txtmatkhau")
        self.btnDangNhap = QtWidgets.QPushButton(self.centralwidget)
        self.btnDangNhap.setGeometry(QtCore.QRect(40, 390, 93, 28))
        self.btnDangNhap.setObjectName("btnDangNhap")
        self.btnThoat = QtWidgets.QPushButton(self.centralwidget)
        self.btnThoat.setGeometry(QtCore.QRect(180, 390, 93, 28))
        self.btnThoat.setObjectName("btnThoat")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(400, 150, 421, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 90, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 281, 161))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icon/logo.ico"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 10, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 90, 51, 41))
        self.label_6.setText("")
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setPixmap(QtGui.QPixmap("icon/warning.ico"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tài Khoản:"))
        self.label_2.setText(_translate("MainWindow", "Mật khẩu:"))
        self.btnDangNhap.setText(_translate("MainWindow", "Đăng nhập"))
        self.btnThoat.setText(_translate("MainWindow", "Thoát"))
        self.label_4.setText(_translate("MainWindow", "Sản phẩm hết hàng"))
        self.label_5.setText(_translate("MainWindow", "Cửa Hàng Bán Phụ Kiện Máy Tính"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
